-- phpMyAdmin SQL Dump
-- version 4.0.4
-- http://www.phpmyadmin.net
--
-- Client: localhost
-- Généré le: Sam 07 Février 2015 à 16:08
-- Version du serveur: 5.6.12-log
-- Version de PHP: 5.4.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Base de données: `primfx`
--

-- --------------------------------------------------------

--
-- Structure de la table `videos`
--

CREATE TABLE IF NOT EXISTS `videos` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `titre` varchar(255) NOT NULL,
  `description` text NOT NULL,
  `urlid` varchar(255) NOT NULL,
  `categorie` varchar(255) NOT NULL,
  `souscategorie` varchar(255) NOT NULL,
  `datedepublication` date NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=134 ;

--
-- Contenu de la table `videos`
--

INSERT INTO `videos` (`id`, `titre`, `description`, `urlid`, `categorie`, `souscategorie`, `datedepublication`) VALUES
(1, 'My first intro ! (JustPrim)', 'Ma première intro', 'f3MG4Mr_loQ', 'Création', 'Intro', '2012-06-10'),
(2, 'Effet de transition "gouttes d''eau"', 'Dans ce tuto vous allez apprendre à créer un effet de transition (pour deux images ou vidéos) dans Adobe After Effects.', 'cNXs0fHz_hs', 'Tuto', 'After Effects', '2012-06-10'),
(3, '#1 Les bases', 'Dans ce tuto, vous allez apprendre les bases du HTML.', '-PYadbLX40g', 'Tuto', 'HTML', '2012-06-10'),
(4, '#2 Les liens et la commande "mailto"', 'Dans ce tuto vous allez apprendre à insérer des liens hypertexts dans votre document HTML et vous allez également apprendre à insérer le commande "mailto" pour permettre aux visiteurs de votre site de vous mailer simplement !', 'TcJ0pPZKtRY', 'Tuto', 'HTML', '2012-06-10'),
(5, 'Appliquer un dégradé à un texte', 'Dans ce tuto vous allez apprendre à appliquer un effet 3D à votre texte sur Photoshop mais aussi à appliquer un dégradé sur un texte.', 'e-Z9HvPNdSU', 'Tuto', 'Photoshop', '2012-06-10'),
(6, 'Avoir le dock de Mac sur Windows', 'Dans ce tuto vous allez apprendre à avoir un dock (la toolbar de Mac) sur un ordinateur Windows grâce à l''application "RocketDock". (compatible Windows 2000/XP/Vista/7)\r\nLien du téléchargement: http://rocketdock.com/download', 'sigqoDGFnAM', 'Tuto', 'Autre', '2012-06-10'),
(7, '#3 Les images', 'Dans ce tuto vous allez apprendre à insérer une couleur de fond, une image de fond, une image dans le html et appliquer des modification à une image en HTML comme la redimensionner, ajouter un bord, l''aligner ou encore insérer un lien quand on clique dessus.', 'hTTdHWkQvjE', 'Tuto', 'HTML', '2012-06-12'),
(8, 'Endorphin - Les bases', 'Dans ce tuto vous allez apprendre les bases du logiciel Endorphin : faire courir puis sauter un personnage. Je sortirai bientôt un prochain tuto vous expliquant comment exporter le fichier utilisé dans ce tuto vers Cinema 4D et ajouter une peau a notre personnage.', 'WmltG_PnsIo', 'Tuto', 'Autre', '2012-06-12'),
(9, 'Animation - De Endorphin à Cinema 4D', 'Dans ce tuto vous allez apprendre à exporter une animation Endorphin vers Cinema 4D (de façon à ajouter une peau à un personnage). Je vais également vous montrer comment y ajouter une belle animation.\r\n\r\nLien des templates des personnages : \r\nwww.packupload.com/JPHH44IH8M4\r\n\r\nFree ".fbx" models : \r\nwww.turbosquid.com/Search/3D-Models/free/fbx', '3ZAxO3ScIi0', 'Tuto', 'Cinema 4D', '2012-06-17'),
(10, 'Intro réalisée pour Gam3rTaG', 'Intro que j''ai réalisé à l''aide de Cinéma 4d et de After Effect pour Gam3rTaG.', 'hukA9Vp5rM8', 'Création', 'Intro', '2012-06-21'),
(11, '#4 Les tableaux', 'Dans ce tuto vous allez apprendre à créer des tableaux, les structurer et les styliser.', 'VwIBhyNcO5o', 'Tuto', 'HTML', '2014-01-11'),
(12, 'Intro PrimFX (C4D, Endorphin et AE) #OLD 2', 'Je vous présente ma nouvelle intro. Quand la chaîne aura atteint les 5000 vues, je ferai un tuto pour vous expliquer comment la réaliser (il sera assez long).', 'yS5fpEfre5U', 'Création', 'Intro', '2012-06-30'),
(13, 'Réglages de rendu HD', 'Dans ce tuto je vais vous apprendre à faire les réglages de rendu Cinema 4D pour que votre vidéo soit rendue en HD au format AVI ou QuickTime.', 'qLQcF6ej6ZY', 'Tuto', 'Cinema 4D', '2012-06-30'),
(14, 'Le Piston', 'Dans ce tuto je vais vous apprendre à créer un piston qui va "briser" un texte dans Cinéma 4D.', 'jhB2Yr-UI0U', 'Tuto', 'Cinema 4D', '2012-07-01'),
(15, 'Cinema 4D - L''ascenseur', 'Voici un ascenseur que j''ai réalisé vite fais sur Cinema 4D.', 'KklDluk5ojI', 'Création', 'Invention', '2012-07-02'),
(16, 'L''ascenseur - Cinema 4D', 'Dans ce tuto je vais vous apprendre à réaliser un ascenseur "simplement" sur Cinema 4D.', '78soIPNwLYw', 'Tuto', 'Cinema 4D', '2012-07-04'),
(17, 'Réaliser une intro exceptionnelle (spéciale 5000 vues !)', 'Dans ce tuto spécial 5000 vues je vais vous apprendre à réaliser ma dernière intro à l''aide des logiciels Cinema 4d, Endorphin et After Effect. Les fichiers (effets sonores et StarWars.lwo) :\r\nwww.packupload.com/QV2KP4QS7PE\r\nVous pouvez télécharger le fichier Cinema 4d de l''intro ici :\r\nwww.mega.co.nz/#!J0VhDKbL!ZGjNSnzFCJhA1RxhbCbwDmFh5SlEBFdkE_Mc2mKz8oA', 'jq1Q3F1v7GM', 'Tuto', 'Cinema 4D', '2012-07-11'),
(18, 'Cinema 4D - Les enceintes (effecteur audio)', 'Voici une petite démo d''enceintes et de barres en mouvement réalisé avec Cinema 4d (en particulier avec l''effecteur audio) sur &quot;Black Tide - Shout&quot;', '-h9WVm49QYM', 'Création', 'Invention', '2012-07-18'),
(19, 'Un texte 3D - Photoshop CS6', 'Dans ce tuto je vais vous apprendre à créer un texte en 3D à partir de PHOTOSHOP CS6 sans aucun autre logiciel.', '9JvBCXwsHfA', 'Tuto', 'Photoshop', '2012-07-20'),
(20, '#5 Les formulaires', 'Dans ce tuto, nous allons voir toutes les possibilités qu''il existe afin de créer un formulaire en HTML.', 'n1z_FkJSWqo', 'Tuto', 'HTML', '2015-01-06'),
(21, 'Modéliser des enceintes (+ effecteur audio) - Cinema 4D', 'Dans ce tuto je vais vous apprendre à vous servir de l''effecteur audio et en même temps à modéliser des haut-parleurs (ou enceintes). Vous pouvez télécharger le fichier .c4d ici :  www.mega.co.nz/#!ItNHzJ5Q!NvsTGx2P4kqM4AOPH84b5zcuN0kA8FzIhJJlnRu3mLg', 'vFHsZ1dTvcY', 'Tuto', 'Cinema 4D', '2012-07-29'),
(22, 'Intro réalisé pour MegaGeekMusic', 'Intro que j''ai réalisé à l''aide de Cinéma 4D et d''After Effects pour MegaGeekMusic.', '1j9vyqPVbl8', 'Création', 'Intro', '2012-07-30'),
(23, 'Intro réalisée pour iPlayGameFR', 'Intro que j''ai réalisé à l''aide de Cinema 4D et d''After Effects pour iPlayGameFR.', 'jjYM2YXNitA', 'Création', 'Intro', '2012-07-30'),
(24, 'Intro réalisée pour LeeQz', 'Intro que j''ai réalisé à l''aide de Cinema 4D et d''After Effects pour LeeQz.', '-xdFSwlEJ_0', 'Création', 'Intro', '2012-08-01'),
(25, 'Créer un effet de tremblement - After Effects', 'Dans ce tuto vous allez apprendre à créer un effet de &quot;tremblement&quot; sur une séquence vidéo avec n''importe quelle version d''Adobe After Effects.', 'IVYdJggB74k', 'Tuto', 'After Effects', '2012-08-08'),
(26, 'Enregistrement et rendu HD sur Camtasio Studio (débutant)', 'Dans ce tuto je vais vous apprendre à enregistrer son écran, sa vois (au micro) et même sa webcam en même temps a l''aide de Camtasia Studio 7 et à faire un rendu de votre enregistrement en HD 720p (1080x720p).', 'l6OFPfNAIDA', 'Tuto', 'Autre', '2012-08-10'),
(27, '#1 - My First Wallpaper - Photoshop CS6 &amp; Cinema 4D R12 [HD]', 'Mon premier Speed Art sur la création d''un background (fond d''écran) avec Photoshop et Cinema 4D.', 'UeKmeyyEqZU', 'Création', 'Speed Art', '2012-08-16'),
(28, 'Créer une GIF animée - Photoshop CS6', 'Dans ce tuto je vais vous apprendre à créer une GIF animée sur Photoshop CS6.', 'cYXaWPF8tBQ', 'Tuto', 'Photoshop', '2012-08-19'),
(29, 'Les bases de Cinema 4D', 'Petit tuto sur ce qui sont POUR MOI les bases de Cinema 4D, les outils dont vous allez le plus vous servir. Bref, pour comprendre, regardez la vidéo !', 'HywmArPlpsI', 'Tuto', 'Cinema 4D', '2012-09-28'),
(30, 'Nuketown Zombie, Black Ops 2 [Online]', 'Salut à tous, aujourd''hui petite vidéo (qui aurait dû être plus tôt sur ma chaîne mais bon... problème informatiques --'' bref.) sur la map Nuketown Zombie (Black Ops 2)...  Regardez-là en 1080p, c''est plus agréable pour vos yeux ! Si la partie coupe à la manche 13, c''est juste que ma connexion à lâchée... désolé mais il fallait que je sorte cette vidéo quand même x) Sur ce, bonne vidéo !', 'aynnyLwVeDY', 'Null', 'Gameplay', '2012-11-16'),
(31, 'Personnaliser le son des notifications Skype', 'Salut tout le monde ! aujourd''hui petite vidéo pour vous montrer comment personnaliser le son des notifications (ex : nouveau message) sur Skype, en remplaçant le son par défaut par un extrait de votre musique préférée !', 'LD5wEZtKx8Y', 'Tuto', 'Autre', '2012-12-02'),
(32, 'Devenir partenaire YouTube rapidement !', 'Salut à tous ! Ajourd''hui petite vidéo pour vous prouver qu''il n''y a pas besoin de 10,000 abonnés et 500,000 vues pour être partenaire YouTube et avoir sa bannière... et oui, vous l''aurez compris, il vous suffit d''avoir une bonne évolution de votre chaîne, quelques connaissances en anglais et voila ! Vous pourrez vous aussi être partenaire YouTube rapidement et facilement grâce au &quot;Socialblade RMP Network&quot; ! Devenez partenaire directement ici : www./awe.sm/gERij  Lien SocialBlade : www.socialblade.com', 'u2B80SveSNE', 'Tuto', 'Autre', '2012-12-05'),
(33, 'Barre de chargement - After Effects', 'Salut les gens, aujourd''hui petite vidéo pour vous montrer comment créer une barre de chargement (ou loading bar) ici sur fond vert, grâce au logiciel Adobe After Effect. Vous pouvez biensur télécharger le fichier &quot;.aep&quot; de la barre ici : www.mediafire.com/download.php?bs9bdq5j9ghccvc', 'XBZ3sFv8bQs', 'Tuto', 'After Effects', '2012-12-29'),
(34, '[COD] 42-14 Hijacked Elim. Conf.', 'Salut tout le monde, aujourd''hui petit gameplay commenté (infos actus de ma chaîne) sur Call Of Duty - Black Ops II, où je fais du 42-14 dans la map Hijacked en élimination confirmée avec l''AN-94 !', 'CTgVL4YAShE', 'Null', 'Gameplay', '2013-02-03'),
(35, 'Souris Roccat Kone XTD', 'Salut les gens, aujourd''hui je vous présente l''unboxing de ma souris gaming Roccat Kone XTD que je trouve vraiment superbe ! Je l''ai depuis maintenant 2 mois environ et l''unboxing a donc été fait au moment où je l''ai eu... Si je ne le met sur ma chaîne que maintenant c''est car j''avais beaucoup d''autres idées de vidéos à faire en attente :)', '8lmpVg4bQUE', 'Null', 'Unboxing et Test', '2013-02-09'),
(36, 'Micro-casque SteelSeries Siberia v2', 'Salut tout le monde... C''est rare que je sorte deux vidéos en un seul jour, mais j''en avais vraiment envie... Bref, je vous propose donc l''unboxing du micro-casque SteelSeries Siberia v2 ;)', '7x2B3p0z2pA', 'Null', 'Unboxing et Test', '2013-02-09'),
(37, 'Exporter en MP4 HD avec Sony Vegas Pro', 'Coucou tout le monde ! Aujourd''hui petit tuto pour vous montrer comment exporter/convertir une vidéo (de n''importe quel format) en MP4 HD tout en gardant sa qualité (contrairement à la plupart des convertisseurs vidéos) grâce au logiciel Sony Vegas Pro (ici 11.0) !', 'NKjz_dHOmKc', 'Tuto', 'Autre', '2013-02-14'),
(38, 'Exporter en PNG ou JPG avec Word ou OpenOffice Writer', 'Salut les gens, aujourd''hui petit tuto pour vous apprendre à exporter un fichier .doc; .odt en image (.png; .jpeg; .jpg;) à partir de Microsoft Word ou OpenOffice Writer et Paint tout bêtement ;)', '1HEU9weuUyE', 'Tuto', 'Autre', '2013-03-27'),
(39, 'Le binaire de A à Z', 'Salut tout le monde, aujourd''hui petit tuto sur le langage binaire ;) j''espère qu''il vous plaira !  Encore merci pour les 400 abonnés ? N''oubliez pas de vous abonner, c''est rapide et sympa !  Lien du traducteur :\r\nhttp://home.paulschou.net/tools/xlate/\r\n\r\nTéléchargement des tableaux :\r\nhttps://mega.co.nz/#!Qh0hgIpL!H5doDwexlmZc0Z7bRCnamxrhyvNNA1GmY9pufAvYg0s\r\n\r\nCode à décrypter :\r\n0101001101101001001000000111010001110101001000000111010000100111011001010111001100100000011000010110001001101111011011100110111001100101001110110010000001101010011001010010000001110100001001110110000101101001011011010110010100111011000011010000101001010011011010010010000001110100011101010010000001101110011001010010000001110100001001110110010101110011001000000111000001100001011100110010000001100001011000100110111101101110011011100110010100111011001000000110011001100001011010010111001100101101011011000110010100100000011001010111010000100000011010100110010100100000011101000010011101100001011010010110110101100101011100100110000101101001011100110000110100001010010100000111001001101001011011010100011001011000011001000110010101110011011010010110011101101110', 'hw1fkUO6ukw', 'Tuto', 'Autre', '2013-03-29'),
(40, 'Présentation de ma nouvelle intro ! (After Effect CS6 - 2D)', 'Compositeur de la zik (en 1ère place dans la description bien sur ;) www.youtube.com/user/TheOfficialHake  Salut les gens, aujourd''hui petite vidéo pour vous présenter ma nouvelle intro réalisée avec uniquement After Effect CS6 (en 2D) qui j''espère va vous plaire !', 'jZbRme9nQkY', 'Création', 'Intro', '2013-03-30'),
(41, 'SocialBlade et LDLC nous font un beau poisson d''avril 2013', 'Salut les gens, aujourd''hui pour le premier avril 2013, SocialBlade et LDLC nous font un beau poisson d''avril ! Mais malheureusement pour eux... je les ais démasqués mouhahahaha et je vais vous en faire part ;)\r\n\r\nSocialBlade : www.socialblade.com/youtube/user/primfxdesign\r\nLDLC : www.ldlc.com/n2496/LDLC+BoX/', 'rdLoa2z8kgI', 'Null', 'Autre Vidéo', '2013-04-01'),
(42, 'Les bases de BodyPaint 3D', 'Salut tout le monde ! Aujourd''hui petit tuto pour vous montrer les bases de BodyPaint 3D, fonctionnalité bien pratique de Cinema 4D que l''on a souvent tendance à oublier...\r\nJe vous laisse donc regarder ce tuto avec pour exemple : texturer un cube de terre minecraft.', 'yDSHOfjLkFg', 'Tuto', 'Cinema 4D', '2013-04-06'),
(43, '#2 - My Second Wallpaper - Photoshop CS6 [HD]', 'Salut tout le monde ! Comme ça fait longtemps que je n''ai pas uploadé de Speed Art sur ma chaîne, je me suis dis que celui de mon nouveau wallpaper (fond d''écran) en serait l''occasion... J''espère donc qu''il vous plaira, n''hésitez pas à laisser vos avis dans les commentaires ;)\r\n\r\nMusique : Bruno Mars - Locked Out Of Heaven', 'SVMDIxxp6wY', 'Création', 'Speed Art', '2013-01-08'),
(44, 'SSD vs HDD - Windows 7 boot', 'HDD : WD Blue 3,5&quot; 1 To (Caviar Blue)\r\nvs\r\nSSD : Samsung 2,5&quot; SSD 840 PRO 128 Go', 'MX5tuLpsJOw', 'Null', 'Autre Vidéo', '2013-04-11'),
(45, '#6 Mettre son site internet en ligne (serveur FTP)', 'Dans ce tuto vous allez apprendre à publier votre site internet (le mettre en ligne sur un serveur FTP) gratuitement.\r\n\r\nLiens :\r\nCyberduck : www.cyberduck.ch/\r\nHébergeur Gratuit : www.hostinger.fr/', 'VM4qZqgASDc', 'Tuto', 'HTML', '2013-04-14'),
(46, '#7 Insérer un élément audio ou vidéo sur son site', 'Dans ce tuto vous allez apprendre à insérer un élément audio (comme une musique) ou un élément vidéo sur votre site internet !', 'xZXiMb35okc', 'Tuto', 'HTML', '2013-04-16'),
(47, 'Réaliser une petite animation avec Cinema 4D et RealFlow', 'Salut tout le monde, aujourd''hui je vous présente un tuto sur un logiciel un peu nouveau (premier tuto dessus) : RealFlow, qui sera accompagné de Cinema 4D, je vais vous apprendre à réaliser une petite animation sympa, qui vous apprendra les bases de RealFlow.\r\n\r\nLien pour le téléchargement du plugin RealFlow pour Cinema 4D (.zip) :\r\nwww.mega.co.nz/#!p5Um0R6a!E3OwxEJ0wT8bieEoABQ-DiAgPJVg7B2NIdoq62v1Wvo', 'lqRdp5VktBw', 'Tuto', 'Cinema 4D', '2013-04-26'),
(48, 'Cinema 4D, RealFlow &amp; After Effects - Animation - 500 Subs ?', 'Salut et un énorme merci au 500 abonnés actuels sur ma chaîne YouTube !!! Ca me fait vraiment plaisir, c''est donc pour cette occasion que j''ai décidé de poster un petit montage très court réalisé avec Cinema 4D, RealFlow et After Effects !', 'RWT7iIXbnKE', 'Null', 'Autre Vidéo', '2013-04-27'),
(49, '#1 Introduction au C++', 'Salut tout le monde, aujourd''hui je vous présente le premier épisode de ma nouvelle série sur le C++ !\r\nJ''espère que cette série vous plaira et vous intéressera !\r\n\r\nLiens pour télécharger code::blocks :\r\n- Windows : http://sourceforge.net/projects/codeblocks/files/Binaries/12.11/Windows/codeblocks-12.11mingw-setup.exe/download\r\n- Mac : http://sourceforge.net/projects/codeblocks/files/Binaries/12.11/MacOS/CodeBlocks-12.11-SP1-mac.zip/download\r\n- Linux : Ouvrir le terminal et taper : apt-get install build-essential codeblocks', 'TUOUsxN3OEg', 'Tuto', 'C++', '2013-05-01'),
(50, '#2 Votre premier (mini mini) programme', 'Salut tout le monde ! \r\nAujourd''hui deuxième épisode de ma série sur le C++, dans cet épisode vous aurez les choses les plus simples à savoir comme afficher du texte mais aussi comprendre les quelques premières lignes affichées par Code::Blocks après la création d''un nouveau projet !', 'oab7BnJnj0o', 'Tuto', 'C++', '2013-05-04'),
(51, '#3 Interactivité, les variables', 'Salut tout le monde !\r\nAujourd''hui nouvel épisode de ma série sur le C++, avec au programme les bases de l''interactivité avec l''utilisateur, nous utiliseront pour cela les variables (nommer une variable, déclarer une variable, utiliser une variable).\r\n\r\nLien pour le tableau des variables : \r\nwww.mega.co.nz/#!ItMCTTiI!LgaepCm_PfU2MJsc3NpUYR3ntNAjWnbSYkFeFcSUaJQ', '8GeJ2DBKy_M', 'Tuto', 'C++', '2013-05-10'),
(52, 'Trailer Xbox 720 [FR] [HD]', 'Petit podcast humoristique pour la pub de la prochaine xBox, façon Apple.... // On s''éclate avec le fond vert !\r\nN''oubliez pas de vous abonner, c''est rapide et sympa !\r\n\r\nCrédits audios :\r\nKidstreet song - www.youtube.com/watch?v=yPP9nMdE_Ks', 'BZydnuFqjUE', 'Null', 'Autre Vidéo', '2013-05-11'),
(53, 'Comment bien débuter sur YouTube by PrimFX', 'Salut tout le monde ! Je vous propose aujourd''hui une vidéo (plus appropriée au débutants) qui vous donnera quelques conseils pour bien débuter sur YouTube en 13 étapes au total !', 'IeDOkw4yG-s', 'Tuto', 'Autre', '2013-05-14'),
(54, '#4 Une vraie calculatrice', 'Un tuto cette fois un peu plus &quot;complexe&quot; sur le C++ mais qui devrait vous plaire, car je vais vous apprendre à faire une vraie calculatrice (de base) uniquement en C++, bien sur sans design, toujours en programme console pour l''instant, n''allons pas trop loin d''un coup !', 'SYKMeDu1yDE', 'Tuto', 'C++', '2013-05-20'),
(55, 'Unboxing - Burn Controller Xbox 360', 'Salut, aujourd''hui petit unboxing de ma nouvelle manette Xbox 360... Une BurnController filaire que j''ai personnalisé avec l''aide de DjebFX !', 'm0Vh_Uk1cwc', 'Null', 'Unboxing et Test', '2013-06-14'),
(56, 'Test - Burn Controller Xbox 360', 'Salut tout le monde ! Aujourd''hui je vous présente le test de ma nouvelle manette Xbox 360 : Une Burn Controller ! Et ce sur un petit gameplay de Black Ops 2 sur la map Hijacked en MME où je fais un score de 26-8 pour 3,25 de ratio', 'o6RQYuF9kvY', 'Null', 'Unboxing et Test', '2013-06-18'),
(57, 'Rendre le démarrage de son PC plus rapide (msconfig)', 'Salut tout le monde, aujourd''hui un tuto très court mais qui pourra se révéler très pratique pour vous permettre de rendre le démarrage de votre ordinateur plus rapide, et ce bien sur sans logiciel ni rien d''autre à télécharger ! (dispo sur Windows uniquement et pas Mac ou Linux)', 'JT1LRxsoi_M', 'Tuto', 'Autre', '2013-06-25'),
(58, '#3 - Wallpaper for TheVals - Photoshop CS6', 'Petit speed art pour changer un peu des tutos et autres vidéos ;p\r\nSur ce je vous laisse le regarder et je vous laisse me dire s''il vous plait dans les commentaires :)', 'RkW3CVeUbC0', 'Création', 'Speed Art', '2013-06-30'),
(59, 'Assembler son PC gamer ! (10min / 1080p)', 'Salut tout le monde ! Je vous propose aujourd''hui un tuto de moins de 10 minutes qui sera (je l''espère) assez complet pour vous montrer comment assembler votre PC.\r\n\r\nVoici ma config :\r\n\r\nBoitier : Xigmatek Talon\r\nProcesseur : Intel Core i7-4770K (3.5GHz)\r\nCarte mère : Asus Maximus VI Hero\r\nCarte graphique : Asus GTX670 2Go\r\nRAM : G.Skill RipJaws X Series 16Go (4x4Go) DDR3 2133MHz\r\nVentirad : Be Quiet ! Dark Rock Pro 2\r\nSSD : Samsung 840 Pro 128Go\r\nDisque Dur : WD caviar blue 1To\r\nAlimentation : Be Quiet ! Pure Power 630W 80PLUS Bronze\r\nVentilateurs :  3x Be Quiet ! Silent Wings 2 140mm &amp; 2x Be Quiet ! Silent Wings 2 120mm       \r\nRheobus : NZXT Sentry LXE\r\nLecteur CD/DVD : Lite-On iHAS 124-04', 'cNR9c39JeGQ', 'Tuto', 'Autre', '2013-06-30'),
(60, 'Tout savoir sur... Fraps !', 'Salut tout le monde ! Aujourd''hui petit tuto pour vous montrer comment vous servir du logiciel très connu Fraps ! J''espère que ce tuto vous plaira.', 'eFjK_WpB4Mo', 'Tuto', 'Autre', '2013-07-07'),
(61, '#4 - Simple New YouTube Banner - Photoshop CS6', 'Aujourd''hui petit speed art pour vous montrer comment j''ai réalisé ma nouvelle bannière YouTube (ou nouveau Background One Channel design), j''espère qu''il vous plaira !', 'Ue7KGUSFdWs', 'Création', 'Speed Art', '2013-07-18'),
(62, 'Faire un montage vidéo synchronisé avec de la musique', 'Aujourd''hui un petit tuto pour vous montrer comment réaliser un montage vidéo synchronisé avec la musique de votre choix, vous pourrez, après avoir vu ce tuto, réaliser de magnifiques montages avec vos films de vacances ou autres clips vidéos :)', 'YvuuCZT38gI', 'Tuto', 'Sony Vegas Pro', '2013-07-26'),
(63, '[INFOS] On parle de l''avenir de ma chaîne', 'Je lance un grand HELP à mes abonnés ! :) Regardez !', 'dqdIXcqkW98', 'Null', 'Vidéo IRL', '2013-08-11'),
(64, 'Tout savoir sur... Action! Mirillis', 'Tuto qui vous montrera toutes les fonctionnalités du logiciel de capture Action! Mirillis,', 'oHsmJFGgKbc', 'Tuto', 'Autre', '2013-08-18'),
(65, '#8 Intégrer un forum à son site internet', 'Pour renforcer un peu plus ma série sur le HTML, je vous propose aujourd''hui un petit tuto pour vous montrer comment insérer un forum sur votre site internet gratuitement et assez facilement !', 'yhepbxmzT8o', 'Tuto', 'HTML', '2013-08-31'),
(66, 'Rendu MP4 HD 1080p rapide d''upload sur YouTube', 'Aujourd''hui un tuto qui sera des plus utiles à tous les YouTubers qui en on assez de devoir passer par des convertisseurs vidéo afin d''avoir des fichiers plus légers à uploader sur YouTube, je vous propose un paramètre de rendu Adobe After Effect qui vous permettra de réunir qualité audio/vidéo et fichier de taille très légère, qui sera donc uploadé sur YouTube beaucoup plus rapidement !', 'VSaigaQSpZo', 'Tuto', 'After Effects', '2013-09-07'),
(67, 'Claviers mécaniques : quel switch choisir ?', 'Petite vidéo pour ceux qui sont perdus avec tous les switchs de clavier mécaniques qu''il existe !\r\n\r\nListe de quelques claviers mécaniques :\r\n\r\nCherry G81-3000\r\n\r\nCooler Master QuickFire TK\r\nCooler Master Storm MECH\r\nCooler Master Storm QuickFire Pro\r\nCooler Master Storm Trigger\r\n\r\nCorsair Vengeance K60 Performance\r\nCorsair Vengeance K65\r\nCorsair Vengeance K65\r\nCorsair Vengeance K70\r\nCorsair Vengeance K90 Performance\r\nCorsair Vengeance K95\r\n\r\nGigabyte Aivia Osmium\r\n\r\nLogitech G710+\r\n\r\nQPAD MK-50\r\nQPAD MK-80\r\nQPAD MK-85\r\n\r\nRazer BlackWindow 2013\r\nRazer BlackWindow Ultimate 2013', 'g6vDL3HA3e0', 'Null', 'Autre Vidéo', '2013-09-14'),
(68, 'Découverte de GTA 5 à ma façon', 'Salut tout le monde, aujourd''hui je vous propose de découvrir le nouveau jeu de Rockstar Games : GTA V (five), je ne vous en dis pas plus pour l''instant :p Bonne vidéo !', 'rDXz-sZMOcA', 'Null', 'Gameplay', '2013-09-18'),
(69, 'Retrouver les anciens modules de sortie (H264, MPEG...)', 'Tuto très court pour vous montrer comment retrouver tous les anciens modules (ou formats) de sortie comme le H.264 ou le MPEG avec la nouvelle version d''After Effect, Adobe After Effect CC !', 'SR6AcPspfxw', 'Tuto', 'After Effects', '2013-09-21'),
(70, '#9 Créer un site internet pas à pas', 'Dans ce tuto, je vais vous apprendre pas à pas comment créer votre premier site internet, de manière très simple (quelques bases seront tout de même nécessaires pour tout comprendre) et ce en 30 minutes !', 's87F83RHiSk', 'Tuto', 'HTML', '2013-10-05'),
(71, 'Souris Logitech G500s', 'Déballage et présentation de la souris Logitech G500s, tous les atouts et les défauts, on parle de chaque recoin de la souris... Bon visionnage !', 'uLq395n3RHw', 'Null', 'Unboxing et Test', '2013-10-12'),
(72, 'Personnaliser son interface + Outils de modélisation polygonale', 'Dans ce tuto je vous apprend à personnaliser votre interface sur Cinema 4D, mais également les principaux outils de modélisation polygonale... Entraînez-vous, car un tuto sur la modélisation d''un objet (quelconque) sera disponible sur ma chaîne !', 'F8A5swOAc3c', 'Tuto', 'Cinema 4D', '2013-10-19'),
(73, 'Carnage avec un tank dans GTA 5 multijoueur', 'Pur carnage avec un tank de la base militaire de GTA V, je vous laisse regarder...', '2jb43DT8ko4', 'Null', 'Gameplay', '2013-10-24'),
(74, 'Graver un CD facilement avec CDBurnerXP', 'Dans ce tuto je vous apprend quelque chose de très simple et pourtant très pratique : Graver un CD facilement et gratuitement grâce au logiciel CDBurnerXP.\r\nLien de téléchargement de CDBurnerXP : \r\nwww.soft.archive2.clubic.com/files/290241c0fffadb8728b688726c9217dd/526d6523/logiciel/cdburnerxp_4-5-2-4291_fr_18424.exe', 'vhnWmI9JWvA', 'Tuto', 'Autre', '2013-10-27'),
(75, 'SetUp + Infos sur ma chaîne !', 'SETUP de mon espace gaming ! (+ quelques infos sur ma chaîne...)', 'HAdTybL9nTQ', 'Null', 'Vidéo IRL', '2013-11-07'),
(76, 'Intro réalisée pour Delano', 'Intro que j''ai réalisé à l''aide d''After Effects pour Delano.\r\nSa chaîne : \r\nwww.youtube.com/user/MrDelanoGaming', 'F1tXyoCpewo', 'Création', 'Intro', '2013-11-09'),
(77, 'Intro réalisée pour TheSly15', 'Intro que j''ai réalisé à l''aide d''After Effects pour TheSly15.\r\nSa chaîne : \r\nwww.youtube.com/user/TheSly15', 'x8cYaoOwW_U', 'Création', 'Intro', '2013-11-14'),
(78, 'Réalisez une intro 2D belle et simple', 'Ce tuto d''une vingtaine de minute vous sera bien utile si vous comptez réaliser votre propre intro en 2D (par suite d''animations), à l''aide du logiciel Adobe After Effect (toutes version).', 'UwZU7B-P4Ak', 'Tuto', 'After Effects', '2013-11-24'),
(79, 'Intro réalisée pour Ex0nGaming', 'Intro que j''ai réalisé à l''aide d''After Effects pour Ex0nGaming.\r\nSa chaîne :\r\nwww.youtube.com/user/Ex0nGaming', 'EQ0IWq2O6NQ', 'Création', 'Intro', '2013-12-07'),
(80, 'Les bases d''Adobe After Effects', 'Tuto d''une demi-heure pour apprendre les bases d''Adobe After Effect. Cette vidéo s''adresse particulièrement à ceux qui n''ont jamais touché à ce logiciel (présentation de l''interface, des principaux outils, etc...).', '5s5D7h0NPqU', 'Tuto', 'After Effects', '2013-12-20'),
(81, 'Cooler Master HAF XB EVO Build', 'Vidéo spéciale Noël ! Build du boitier HAF XB EVO de Cooler Master...', '8VszqV4zmUE', 'Null', 'Vidéo IRL', '2013-12-24'),
(82, 'GTA 5 - Les défis en folie - #1 Présentation', 'Bonjour à tous, je vous présente aujourd''hui une idée de série sur GTA 5... Dites-moi, en commentaire, si le projet vous plaît, proposez vos défis ou participez-y !', 'Qb6YKrwNc4k', 'Null', 'Gameplay', '2013-12-29'),
(83, 'GTA 5 - Les défis en folie - #2 Si les camions étaient des Ferrari', 'Aujourd''hui nouveau défis qui consiste à monter en haut de Mont Chiliad en semi-remorque... Ce qui ne sera pas aussi facile qu''on le pensait. Cette course en semi-remorque sera donc légèrement dérivée, mais je vous laisse voir le résultat !', 'T23mLvsL1cc', 'Null', 'Gameplay', '2014-01-03'),
(84, 'Quoi de neuf sur ma chaîne en 2014 ?', 'Bonne année à tous !\r\nJe vous propose une petite vidéo IRL pour introduire cette nouvelle année, dans laquelle je parlerai de tous mes projets et des séries qui vont sortir (ou qui sont déjà sorties) :)', 'kz8DCYXSCTU', 'Null', 'Vidéo IRL', '2014-01-08'),
(85, '#1 Les bases', 'Dans ce premier épisode sur le CSS (Cascading Style Sheet), je vais vous montrer ce qu''il est possible de faire avec ce fabuleux langage qui vient compléter la série sur le HTML que j''avais déjà faite. Je vais également vous apprendre à insérer du CSS dans un document HTML de plusieurs façons et vous présenter la syntaxe de ce code.', '_-KEFeWLVtY', 'Tuto', 'CSS', '2014-01-12'),
(86, 'GTA 5 - Les défis en folie - #3 Si le Cargobob était un Taxi', 'Nouvel épisode des défis en folie sut GTA 5, résumé de la vidéo en un seul mot : FUN !\r\nChaîne de DjebFX : \r\nwww.youtube.com/user/djebfx\r\nChaîne de Kalys : pas encore de chaîne :p', 'LVAYhqIT3R4', 'Null', 'Gameplay', '2014-01-19'),
(87, '#2 Couleurs et arrières-plans', 'Deuxième tuto de la série CSS, de nouvelles choses très basiques mais aussi importantes à connaître !', 'j3mpsc1RO-w', 'Tuto', 'CSS', '2014-01-26'),
(88, 'Cartes d''acquisition 2014 #HDPVR', 'Voilà pour ceux qui veulent en savoir plus sur les HD PVR, plus particulièrement de cette année ! Si j''ai oublié quelques informations essentielles, rajoutez-les en commentaire :p Au programme descriptif et comparaison de différentes cartes d''acquisition vidéo chez les marques Hauppauge et AverMedia !', 'DpsMUyY3wzI', 'Null', 'Autre Vidéo', '2014-02-07'),
(89, '#3 Les polices', 'Aujourd''hui on parle des polices en CSS, les propriétés &quot;font-style, -variant, -weight, -size et -family&quot; ! Alors à vos NotePads ! ', 'bdeVDDY-qCc', 'Tuto', 'CSS', '2014-02-16'),
(90, 'Mon site enfin update et en ligne ! - PrimFX.com', 'Mon site ( http://www.primfx.com) est enfin, comme promis, mis à jour et disponible ! Donnez vos avis sur mon site et ce que je pourrais améliorer ou y ajouter en commentaire !', 'Vsj3YwNybAk', 'Null', 'Vidéo IRL', '2014-02-22'),
(91, '#4 Formatage de texte', 'Dans ce tuto CSS, on parlera du formatage de texte, c''est-à-dire de toutes les décorations et propriétés liées au texte (text-decoration, text-align,...) !', '8_cfVYLvsn0', 'Tuto', 'CSS', '2014-03-09'),
(92, '#5 Les liens', 'Tuto CSS assez court qui vous permettra de savoir comment personnaliser vos liens, on parlera d''un nouveau terme du CSS : les &quot;pseudo-classes&quot; !', 'RY9GJZXoRng', 'Tuto', 'CSS', '2014-03-16'),
(93, 'Présentation projet 2000 abonnés', 'Vidéo IRL pour vous présenter mon petit projet spécial 2000 abonnés: une F.A.Q. !\r\nPosez-moi vos questions :\r\n- En commentaire de cette vidéo,\r\n- via Facebook : \r\nwww.facebook.com/primfxdesign\r\n- ou via Twitter : \r\nwww.twitter.com/primfx', '_lim_BqzgUc', 'Null', 'Vidéo IRL', '2014-03-19'),
(94, 'A la recherche du skill - Sondage &amp; Fun - Battlefield 4', 'Petite vidéo fun (un peu) avec sondages (écoutez bien !) et blabla inutile au programme... Bon visionnage ;-)', '9r3oe_1vUo0', 'Null', 'Gameplay', '2014-03-30'),
(95, 'C''est la Kata ! - League of Legends - Feat. DjebFX', 'Petite vidéo détente et fun en mode zapping sur League of Legends en compagnie de DjebFX :-)', '8CAJwNfqyTM', 'Null', 'Gameplay', '2014-04-06'),
(96, '#6 Sélecteurs Class et ID', 'Dans ce tuto nous allons parler d''une des plus importantes étapes de l''apprentissage du CSS, qui nous permettra par la suite d''entrer dans le vif du sujet... Soyez donc bien attentifs à ces sélecteurs Class et ID, et rendez-vous très bientôt pour un prochain épisode !', 'q5I3vuo6PCw', 'Tuto', 'CSS', '2014-04-19'),
(97, '#10 Les favicons', 'Les favicons, ces petites miniatures de pages web, parfois bien embêtantes à insérer sur votre site... Apprenez dès à présent comment en créer et en intégrer une facilement !', 'cadq3Zc6HYQ', 'Tuto', 'HTML', '2014-05-09'),
(98, 'Laa-Laa fait de la breakdance - Slendytubbies - Feat. Audrey', 'On avait envie de se faire une petite frayeur hier avec Audrey du coup on a installé la bêta de Slendytubbies :-) Je vous laisse admirer nos réactions face aux Teletubbies de l''enfer...', 'CJ5D70uMTwo', 'Null', 'Gameplay', '2014-05-17'),
(99, 'Débattons sur AdBlock - Les pour et les contres du nouveau phénomène de la toile', 'A ce jour, un grand nombre de personnes se servent d''AdBlock (ou de plugins semblables) un peu partout dans le monde. Mais savez-vous vraiment comment ce petit plugin fonctionne et quel impacte a-t-il ou bien aura-t-il sur le net dans les prochaines années, voir les prochains mois à venir ? Non ? Alors après avoir regardé cette vidéo de présentation, n''hésitez pas à partager vos idées et opinions en commentaires afin d''en débattre avec d''autres internautes !\r\n\r\nSources :\r\nhttp://adunblock.com/blog/posts/2-comment-fonctionne-adblock-cie\r\nhttp://formation-universite-web-reseaux-sociaux.com/2013/11/le-phenomene-adblock-plus-la-fin-de-lage-dor-pour-les-annonceurs-en-ligne/\r\nhttp://maniacgeek.net/2012/07/02/quels-sont-les-revenus-possibles-avec-adsense-sur-son-blog-3998\r\nhttps://addons.mozilla.org/fr/firefox/addon/adblock-plus/statistics/?last=30', 'OpWTNkOJ-l8', 'Null', 'Vidéo IRL', '2014-05-24'),
(100, 'C''est l''heure de la victimisation - Gang Beasts - Feat. Mr Bizigu', 'Gameplay sur Gang Beasts en compagnie de Mr Bizigu (Louis) \r\nPour info, je suis le bonhomme bleu et Louis est le rouge', 'HMTj1fndWZU', 'Null', 'Gameplay', '2014-05-30'),
(101, 'Bientôt les vacances ! :D', 'Petite vidéo webcam pour m''excuser de mon inactivité depuis plusieurs semaines sur ma chaîne YouTube, comme dis les vidéos reviennent dès le début des grandes vacances :-) Encore bonne chance à ceux qui passent des examens genre brevet &amp; bac et à bientôt pour de nouvelles vidéos !', '2pLeX4dlt5A', 'Null', 'Vidéo IRL', '2014-06-22'),
(102, '#7 Regroupement d''éléments avec span et div', 'Nous avons appris précédemment à utiliser les balises Class et ID, voyons maintenant comment bien les utiliser :-)', '3H_aQZ9wtGo', 'Tuto', 'CSS', '2014-06-28'),
(103, 'L''Optimizeur - #1 Optimiser son disque dur', 'Dans cette série que j''ai baptisé &quot;L''Optimizeur&quot;, je vous montrerai en plusieurs épisodes trucs &amp; astuces pour optimiser les performances de votre ordinateur et le rendre plus rapide !\r\n\r\nEtant donné qu''il s''agit du premier épisode de la série, je vous remercierai de bien vouloir commenter (positivement ou négativement) afin de me donner des conseils pour améliorer la qualité des prochains épisodes.\r\n\r\nVous pouvez également me faire part des bugs / lags qui touchent votre PC pour que j''essaie d''y trouver remède et pourquoi pas poster ça dans de prochaines vidéos si le problème en question affecte beaucoup d''ordinateurs !\r\n\r\nJ''espère donc que cette série vous plaira et surtout qu''elle vous sera utile. On commence donc par cet épisode dans lequel on parlera de l''optimisation de son/ses disque(s) dur(s) :-)\r\n\r\nLiens utiles (télécharger les versions gratuites &quot;Free&quot; ):\r\nTélécharger EaseUS Partition Master :\r\nwww.easeus.com/download/epmf-download.html\r\nTélécharger CCleaner : \r\nwww.piriform.com/ccleaner/download\r\n\r\nPS: Désolé pour le curseur qui bloque par moment, bug dû à mon logiciel de capture (que j''aurais normalement réglé d''ici les prochains épisodes...)\r\nPS2: Veuillez aussi m''excuser pour mon inactivité sur ma chaîne ces derniers temps :p', '8rOYPyTIf_Q', 'Tuto', 'Autre', '2014-08-02'),
(104, 'Mise à jour de PrimFX.com... Surprise ! :-)', 'Aujourd''hui petite vidéo de présentation de la nouvelle fonctionnalité de mon site internet... Je ne vous laisse découvrir en vidéo !\r\n\r\nMon site internet : www.primfx.com\r\n\r\nLien mobile du chat : http://goo.gl/ATnfWw', 'BauBVuDZNqw', 'Null', 'Autre Vidéo', '2014-08-08'),
(105, 'PrimFX.com - Trailer - Nouvelle interface', 'Trailer de la nouvelle update de mon site...\r\nwww.primfx.com\r\n\r\nMusique: Heart of courage - Two steps from hell', 'LHJ_NVKpxu0', 'Null', 'Autre Vidéo', '2014-08-13'),
(106, 'L''Optimizeur - #2 Le grand nettoyage', 'Deuxième épisode de la série ! C''est votre PC qui vous dira merci ;-)\r\nOn verra dans ce tuto quels logiciels sont utiles au nettoyage de votre ordinateur et pourquoi, avec une petite présentation pour chacun de ces logiciels !\r\n\r\nLiens de téléchargement :\r\n- CCleaner : http://goo.gl/wBJQ1X\r\n- avast! Free Antivirus : http://goo.gl/POVLqQ\r\n- Malwarebytes Anti-Malware : http://goo.gl/ocAFwj\r\n- ZoneAlarm Security (attention aux éventuelles pubs lors de l''installation; voir sur la page de téléchargement !) : http://goo.gl/wvJlrP\r\n- AdwCleaner : http://goo.gl/aDC4io', '-qG2oTd7G-0', 'Tuto', 'Autre', '2014-08-15'),
(107, 'L''Optimizeur - #3 Optimiser son interface', 'Troisième (et normalement dernier) épisode de la série &quot;L''Optimizeur&quot;, on s''intéressera dans ce tuto à améliorer l''interface de votre Windows afin de la rendre plus fluide !\r\n\r\nTéléchargements :\r\n- Classic Shell : http://goo.gl/biVIsZ\r\n- Fichier .xml pour Classic Shell : http://goo.gl/3GBHhX', 'T7JEvMylFKo', 'Tuto', 'Autre', '2014-08-16'),
(108, 'Qu''est-ce que le Flat Design ?', 'Dans cette vidéo je vais vous montrer ce que signifie la notion de &quot;Flat Design&quot; qui est beaucoup utilisé ces temps-ci. On comparera aussi ce design au design skeuomorphic qui est en quelques sortes son &quot;concurrent&quot; direct.\r\n\r\nSources :\r\nwww.downgraf.com/inspiration/20-awesome-examples-of-skeuomorphism-in-web-design/#prettyPhoto\r\nhttp://blog.lunaweb.fr/interface-flat-design/\r\nhttp://blog.gaborit-d.com/dossier-quest-ce-que-le-flat-design/\r\nwww.youtube.com/watch?v=tv4PzLGYP3Y\r\nhttp://blog.octo.com/le-flat-design-plus-quune-mode/\r\nhttps://vimeo.com/45367790', 'FZ4UUfGWnCA', 'Null', 'Vidéo IRL', '2014-08-30'),
(109, '#8 Les boîtes', 'Nouveau tuto de la série CSS dans lequel on va réellement commencer à parler design ! Je vous laisse voir par vous-même ;-)', 's3zQQhAvjT4', 'Tuto', 'CSS', '2014-09-05'),
(110, 'Présentation du projet 3000 abonnés !', 'VIDEO REPONSE DISPO ICI : \r\nwww.youtube.com/watch?v=mmQfFck4v-Y\r\n\r\nMerci à tous d''être aussi nombreux à me suivre ! Pour les 3000 abonnés je vous propose une petite F.A.Q. :-)\r\n\r\nPoses ta ou tes question(s) en commentaire de cette vidéo ou à une de ces adresses avec le #AskPrimFX !\r\n- www.twitter.com/primfx\r\n- www.facebook.com/primfxdesign\r\n\r\nJe répondrais à vos questions dans une prochaine vidéo dès les 3000 atteints !\r\n\r\nPour voir la F.A.Q. #1 c''est par ici : \r\nwww.youtube.com/watch?v=--IsLaEZj6I', 'ddUqkBK_7Lk', 'Null', 'Vidéo IRL', '2014-09-13'),
(111, '#9 Les éléments flottants', 'Dans ce petit tuto nous allons pousser plus loin ce que je vous ai montré dans d''anciens tutos comme le regroupement d''éléments (avec class et ID) ou les boîtes !', '8WVonZcin6Y', 'Tuto', 'CSS', '2014-09-20'),
(112, '#10 Le positionnement d''éléments', 'Tuto CSS dans lequel je vais vous montrer comment positionner vos éléments, plus précisément vos boîtes, avec la propriété &quot;position&quot;...', 'UaRn68wHCg8', 'Tuto', 'CSS', '2014-09-28'),
(113, '#11 Indexation de calques (z-index)', 'Dans ce tuto, nous allons uniquement parler de la propriété z-index qui pourra vous être bien utile pour gérer &quot;l''empilement&quot; des différentes boites de votre site et éventuellement corriger certains problèmes d''affichage par défaut !', 'cReqUlKaJAU', 'Tuto', 'CSS', '2014-10-04'),
(114, 'Présentation d''un nouveau projet... A découvrir !', 'Présentation d''un nouveau projet en collaboration avec DjebFX !\r\nBande annonce du court-métrage : \r\nwww.youtube.com/watch?v=EI0TXI3Dt1U\r\nFlashback Broadcast : \r\nwww.youtube.com/user/flashbackbroadcast\r\n\r\nPS: Désolé pour cette vidéo faite un peu à l''arrache mais disons que j''étais un peu en retard niveau timing xD', 'gJJjpwdv9NA', 'Null', 'Vidéo IRL', '2014-10-11'),
(115, 'F.A.Q. #2 - Spéciale 3000 abonnés !', 'Petite vidéo pour vous remercier d''être déjà 3000 à me suivre !\r\n\r\nFlashback Broadcast : \r\nwww.youtube.com/user/flashbackbroadcast\r\n\r\nLiens des chaînes des poseurs de questions... :\r\n- www.youtube.com/user/AurelienGraffiti\r\n- www.youtube.com/user/misterkiller68\r\n- www.youtube.com/channel/UCWsNm5HNAT5oT6dVfd-Ayfg', 'mmQfFck4v-Y', 'Null', 'Vidéo IRL', '2014-10-19'),
(116, 'On pédale comme des hamsters - Trials Fusion - Feat. Mr Bizigu', 'Aujourd''hui je vous propose une petite vidéo gaming (histoire de changer un peu) sur Trials Fusion en compagnie de Louis (Mr Bizigu) !', 'df1_TRBNCD8', 'Null', 'Gameplay', '2014-10-25'),
(117, '#12 Media Queries', 'Dans ce tuto CSS on va parler des Media Queries. J''ai essayé de ne pas faire trop long parce qu''il y a énormément de choses à dire à ce sujet, mais j''espère que l''ensemble sera tout de même assez complet ! ;-)\r\nSi vous voulez plus de renseignements sur l''utilisation de cet outil magique, je vous laisse visiter ce site: \r\nwww.alsacreations.com/article/lire/930-css3-media-queries.html', 'CFmse9aEUIA', 'Tuto', 'CSS', '2014-11-08'),
(118, 'HTML &amp; CSS - Créer un site internet de A à Z', 'Dans ce tuto, vous apprendrez à créer entièrement un site internet en HTML et CSS. Il est cependant préférable d''avoir acquis au préalable quelques notions de bases de ces langages pour mieux comprendre la vidéo ! Si vous avez des questions n''hésitez pas à utiliser l''espace commentaire ou les réseaux sociaux ;-)\r\n\r\nVous pouvez télécharger le site ici: https://mega.co.nz/#!Ew1VEI7J!1MKEx5ADDQx2xz5PGP0WRbKFsJjo_9JXrUnva2pGSts', 'z1KDrCFz1QM', 'Tuto', 'HTML', '2014-11-14'),
(119, 'Vous avez dit PHP ?', 'Petite vidéo IRL pour vous présenter le déroulement de ma prochaine série sur le PHP (qui sera par la suite complémentée par du MySQL)... Vous n''avez plus qu''à laisser vos conseils en commentaire pour que la série soit le mieux possible !', 'B2cvoIBu8OQ', 'Null', 'Vidéo IRL', '2014-11-22'),
(120, '#1 Les pré-requis', 'Premier tuto de la série PHP ! Je vais simplement vous parler un peu des pré-requis qu''il vous faudra pour pouvoir suivre cette série.\r\nVous pouvez aussi suivre cette série en live sur Twitch le samedi soir ( www.twitch.tv/primfx ) ;-)\r\n\r\nLiens de téléchargement :\r\nWAMP : www.wampserver.com/\r\nMAMP : www.mamp.info/\r\nXAMPP : www.apachefriends.org/fr/\r\nSublime Text : www.sublimetext.com/2', 'eoa_Q6-HTIo', 'Tuto', 'PHP', '2014-12-07'),
(121, 'Accélérer phpMyAdmin sur Wamp', 'Tuto très court dans lequel vous allez voir comment accélérer efficacement et simplement phpMyAdmin !\r\n\r\nScript (à coller dans: &quot;C:\\wamps\\apps\\phpmyadminx.x.x\\config.inc.php&quot;) :\r\n\r\n$cfg[''ExecTimeLimit''] = 0;\r\n$cfg[''LeftFrameLight''] = true;\r\n$cfg[''PersistentConnections''] = true;', 'TSDslv4CU2s', 'Tuto', 'Autre', '2014-12-09'),
(122, '#2 Les variables', 'Dans ce deuxième tuto PHP, nous allons apprendre à connaître les variables. Il s''agit d''une étape fondamentale à l''apprentissage de ce langage et de tout autre langage de programmation ! Les variables sont un outil dont nous nous serviront, à partir d''aujourd''hui, dans tous les prochains tutos de la série ! Bien sûr, si vous avez des questions, n''hésitez pas ;-)\r\n\r\nLiens utiles :\r\n\r\nhttp://zupimages.net/up/14/50/jpzl.jpg\r\nhttp://zupimages.net/up/14/50/cv22.jpg', 'NWnB_cNHh54', 'Tuto', 'PHP', '2014-12-14'),
(123, 'PrimFX - Bande annonce', 'Salut, je suis PrimFX et tu es le bienvenu sur ma chaîne YouTube ! Si tu as aimé cette vidéo, je t''invite à aller voir les autres disponibles sur ma chaîne...', 'ekOOUHZAW1w', 'Null', 'Autre Vidéo', '2014-12-17'),
(124, '#3 Les conditions', 'Dans ce troisième épisode de la série PHP, nous allons parler des conditions avec les structures &quot;if, elseif, else&quot; et &quot;switch&quot;.', 'ylSx1cmvMxQ', 'Tuto', 'PHP', '2014-12-20'),
(125, 'Audio-Technica ATR3350', 'Petite vidéo unboxing et test du micro-cravate Audio-Technica ATR3550 que vous pouvez retrouver ici : http://goo.gl/ZRW9cJ', 'cj08-HoQQfE', 'Null', 'Unboxing et Test', '2014-12-21'),
(126, '#4 Les boucles', 'Même si les boucles sont très peu utilisées en PHP (excepté pour la lecture dans les bases de données, mais nous n''y sommes pas encore...), il est important de les connaître car il s''agit d''un principe fondamental en programmation (dans tous les langages)... C''est pourquoi je vous propose un tuto sur ces fameuses boucles (en utilisant while et for)', '4Tw9TwLvs0Y', 'Tuto', 'PHP', '2014-12-27'),
(127, 'Quoi d''neuf sur ma chaîne en 2015 ?', 'Je vous souhaite une très bonne année 2015 et je vous propose cette vidéo IRL afin de vous présenter mes projets pour 2015... Surprise !\r\n\r\nSi vous ne savez pas quoi prendre comme résolutions pour cette nouvelle année, je ne peux que vous conseiller de prendre du 4K ! :D (c''était la p''tite blague geek du jour...)\r\n\r\nChaînes dont j''ai parlé dans cette vidéo : \r\nFlashback Broadcast : http://goo.gl/q1oQnH\r\nWeGotABigCoC FR : http://goo.gl/WkLRwU\r\nDjebFX : http://goo.gl/6rk8ws', 'NJ42occ9S8w', 'Null', 'Vidéo IRL', '2014-12-31'),
(128, '#5 Transmettre des informations par formulaire', 'C''est dans ce tuto PHP que nous entrons dans le vif du sujet... Tout ce que nous avons vu précédemment faisait plus parti des bases qu''il faut avoir dans ce langage. Avec le transfert de données par formulaires, vous pourrez commencer à avoir une interaction avec vos internautes.\r\nLa prochaine grande étape sera le transfert d''informations vers une bases de données et la récupération de celles-ci sur votre site !', '0cGOrzqEQq0', 'Tuto', 'PHP', '2015-01-03'),
(129, '#6 Variables de session et cookies', 'Les variables de session et les cookies sont essentiels à connaître si vous souhaitez un jour créer un site avec un espace membre, un forum ou quoi que ce soit d''autre du même genre !', 'A2U64YRN86s', 'Tuto', 'PHP', '2015-01-10'),
(130, 'Question à Tous mes abonnés ! :-)', 'Bonjour à tous ! Je me rend compte que mes vidéos sont assez &quot;sélectives&quot; et ne peuvent malheureusement pas intéresser tout le monde... C''est pourquoi j''ai décidé de vous proposer un contenu plus &quot;ouvert&quot; en faisant des petits vlogs sur le high-tech, parfois mes projets, mais aussi en répondant à vos questions au début de chaque vlog avec le #AskPrimFX sur Twitter !\r\n\r\nJ''espère que cette petite initiative de ma part vous plaira, je vous laisse donner votre avis en commentaire et vous souhaite encore une très bonne année 2015 ! ;-)\r\n\r\nPS: Pleins de bonnes choses à venir pour cette année... *Comme un concours ?... :p*', 'rqsq9Cx5ZWU', 'Null', 'Vidéo IRL', '2015-01-13'),
(131, '#7 Interagir avec un fichier', 'Interagir avec des fichiers en php c''est comme une sorte d''initiation à l''utilisation de bases de données mais en tout petit... Nous verrons ça dans les prochains tutos ;-)', 'h4eNlaz61BQ', 'Tuto', 'PHP', '2015-01-17'),
(132, '#1 Lunettes Gunnar, mon avis', 'Premier vlog de ma vie (vous me direz ce que vous en pensez :p)\r\nJe vous propose de parler un peu des Gunnar et j''aurai une petite surprise pour vous à la fin de la vidéo...', '1XYZ3oqIIfo', 'Null', 'Vlog', '2015-01-20'),
(133, '#8 Introduction à phpMyAdmin plussymb', 'phpMyAdmin est un outil qui vous permettra de gérer vos bases de données, tables et entrées que vous pourrez modifier comme vous le souhaitez à partir de votre site internet grâce aux requêtes SQL (nous aborderons ça dans un prochain épisode :p) !', '0DL-MeAvWz4', 'Tuto', 'PHP', '2015-01-23');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
